print("Підписуємо зошит")
lessons = input("Вкажи з якого предмету: ")
group = input("Вкажи свій клас: ")
school = input("Вкажи свій навчальний заклад: ")
surname = input("Вкажи своє прізвище: ")
name = input("Вкажи своє ім'я: ")
print("Зошит")
print(lessons)
print("ліцеїста групи", group)
print(school)
print(surname, name)